import { describe, expect, it } from 'vitest'
import {
  isAutoGeneratedSectionId,
  slugifySectionTitle,
  uniqueSectionSlug,
} from './curriculumSlug'

describe('slugifySectionTitle', () => {
  it('slugifies human titles', () => {
    expect(slugifySectionTitle('Data and APIs')).toBe('data_and_apis')
  })

  it('returns empty for blank titles', () => {
    expect(slugifySectionTitle('   ')).toBe('')
  })
})

describe('isAutoGeneratedSectionId', () => {
  it('matches pending section ids', () => {
    expect(isAutoGeneratedSectionId('section_mpzkuxhh')).toBe(true)
    expect(isAutoGeneratedSectionId('data_and_apis')).toBe(false)
  })
})

describe('uniqueSectionSlug', () => {
  it('appends numeric suffix when taken', () => {
    expect(uniqueSectionSlug('fundamentals', ['fundamentals'])).toBe('fundamentals_2')
  })
})
