import type { LanguageBundle } from '../curriculum/types'
import { cloneBundle } from './curriculumPatch'

/** IDs from `newId('section')` before the section is named. */
export function isAutoGeneratedSectionId(id: string): boolean {
  return /^section_[a-z0-9]+$/.test(id)
}

export function slugifySectionTitle(title: string): string {
  const slug = title
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/_+/g, '_')
  return slug
}

export function uniqueSectionSlug(base: string, taken: Iterable<string>): string {
  const used = new Set(taken)
  if (!used.has(base)) return base
  let n = 2
  while (used.has(`${base}_${n}`)) n++
  return `${base}_${n}`
}

export function renameSectionInBundle(
  bundle: LanguageBundle,
  oldId: string,
  newId: string,
  title: string,
): LanguageBundle {
  const path = `${newId}.json`
  const next = cloneBundle(bundle)
  for (const sec of next.index.sections) {
    if (sec.id === oldId) {
      sec.id = newId
      sec.title = title
      sec.path = path
    }
  }
  for (const loaded of next.sections) {
    if (loaded.sectionRef.id === oldId) {
      loaded.sectionRef.id = newId
      loaded.sectionRef.title = title
      loaded.sectionRef.path = path
      loaded.file.sectionId = newId
      loaded.file.title = title
    }
  }
  return next
}
