import {
  useCallback,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from 'react'
import type {
  Challenge,
  LanguageBundle,
  Level,
  RootIndex,
  TestQuestion,
} from '../curriculum/types'
import { moveItem, removeAt } from './arrayHelpers'
import { mergeAboutContent, type AboutContent } from './aboutContent'
import { ConfirmDialog } from './ConfirmDialog'
import { cloneBundle, cloneRootIndex, patchBundle, patchSectionLevels as patchBundleSectionLevels } from './curriculumPatch'
import { loadLanguageBundle, loadRootIndex } from '../curriculum/loadCurriculum'
import {
  createDefaultChallenge,
  createDefaultLanguage,
  createDefaultLevel,
  createDefaultMcqQuestion,
  createDefaultSection,
  createDefaultShortTextQuestion,
  newId,
} from './curriculumDefaults'
import {
  loadDraftAbout,
  loadDraftBundle,
  loadDraftHomeLead,
  loadDraftRootIndex,
  loadContentSource,
  saveContentSource,
  saveDraftAbout,
  saveDraftBundle,
  saveDraftHomeLead,
  saveDraftRootIndex,
  type ContentSource,
} from './curriculumDraftStorage'
import { canEditContent, subscribeGitHubAuth } from './editorAuth'
import { downloadJson } from './exportCurriculum'
import { saveCurriculumToGitHub } from './githubCurriculumApi'
import { DEFAULT_HOME_LEAD } from './editorConstants'
import { EditorContext } from './editorReactContext'
import {
  isAutoGeneratedSectionId,
  renameSectionInBundle,
  slugifySectionTitle,
  uniqueSectionSlug,
} from './curriculumSlug'

export interface EditorContextValue {
  canEdit: boolean
  isEditMode: boolean
  setEditMode: (value: boolean) => void
  toggleEditMode: () => void

  contentSource: ContentSource
  setContentSource: (source: ContentSource) => void
  githubHomeLead: string

  rootIndex: RootIndex | null
  syncRootIndex: (fetched: RootIndex) => void
  updateLanguage: (langId: string, patch: { title?: string; id?: string }) => void
  updateHomeLead: (text: string) => void
  homeLead: string

  getBundle: (langId: string) => LanguageBundle | null
  syncBundle: (langId: string, fetched: LanguageBundle) => void
  updateLanguageTitle: (langId: string, title: string) => void
  updateSectionTitle: (langId: string, sectionId: string, title: string, options?: { commit?: boolean }) => void
  updateLevelTitle: (langId: string, sectionId: string, levelId: string, title: string) => void
  updateLevelIntro: (
    langId: string,
    sectionId: string,
    levelId: string,
    patch: Partial<Level['intro']>,
  ) => void
  updateChallenge: (
    langId: string,
    sectionId: string,
    levelId: string,
    challengeId: string,
    patch: Partial<Challenge>,
  ) => void
  updateTestPassingScore: (
    langId: string,
    sectionId: string,
    levelId: string,
    score: number,
  ) => void
  updateTestQuestion: (
    langId: string,
    sectionId: string,
    levelId: string,
    questionId: string,
    question: TestQuestion,
  ) => void

  requestConfirm: (message: string) => Promise<boolean>

  addLanguage: () => string | null
  removeLanguage: (langId: string) => void
  moveLanguage: (langId: string, direction: -1 | 1) => void

  addSection: (langId: string) => string | null
  removeSection: (langId: string, sectionId: string) => void
  moveSection: (langId: string, sectionId: string, direction: -1 | 1) => void

  addLevel: (langId: string, sectionId: string) => string | null
  removeLevel: (langId: string, sectionId: string, levelId: string) => void
  moveLevel: (langId: string, sectionId: string, levelId: string, direction: -1 | 1) => void

  addChallenge: (langId: string, sectionId: string, levelId: string) => string | null
  removeChallenge: (langId: string, sectionId: string, levelId: string, challengeId: string) => void
  moveChallenge: (
    langId: string,
    sectionId: string,
    levelId: string,
    challengeId: string,
    direction: -1 | 1,
  ) => void

  addTestQuestion: (
    langId: string,
    sectionId: string,
    levelId: string,
    type: 'mcq' | 'shortText',
  ) => string | null
  removeTestQuestion: (
    langId: string,
    sectionId: string,
    levelId: string,
    questionId: string,
  ) => void
  moveTestQuestion: (
    langId: string,
    sectionId: string,
    levelId: string,
    questionId: string,
    direction: -1 | 1,
  ) => void

  addAboutInstallStep: () => void
  removeAboutInstallStep: (index: number) => void
  moveAboutInstallStep: (index: number, direction: -1 | 1) => void

  aboutContent: AboutContent
  initAboutContent: (platformSteps: string[]) => void
  updateAboutLead: (text: string) => void
  updateAboutInstallIntro: (text: string) => void
  updateAboutInstallStep: (index: number, text: string) => void

  exportRootIndex: () => void
  exportLanguageIndex: (langId: string) => void
  exportSection: (langId: string, sectionId: string) => void

  importFromGitHub: (baseUrl: string) => Promise<void>
  saveToGitHub: (onProgress?: (label: string, index: number, total: number) => void) => Promise<void>
}

function useCanEdit(): boolean {
  const [canEdit, setCanEdit] = useState(() => canEditContent())
  useEffect(() => subscribeGitHubAuth(() => setCanEdit(canEditContent())), [])
  return canEdit
}

export function EditorProvider({ children }: { children: ReactNode }) {
  const canEdit = useCanEdit()
  const [isEditMode, setEditMode] = useState(false)
  const [contentSource, setContentSourceState] = useState<ContentSource>(() => loadContentSource())
  const [rootIndex, setRootIndex] = useState<RootIndex | null>(() => loadDraftRootIndex())
  const [bundles, setBundles] = useState<Record<string, LanguageBundle>>({})
  const [homeLead, setHomeLead] = useState(
    () => loadDraftHomeLead() ?? DEFAULT_HOME_LEAD,
  )
  const [aboutContent, setAboutContent] = useState<AboutContent>(() => {
    const draft = loadDraftAbout()
    return draft ?? mergeAboutContent([], null)
  })
  const [aboutInitialized, setAboutInitialized] = useState(false)
  const [confirmState, setConfirmState] = useState<{
    message: string
    resolve: (value: boolean) => void
  } | null>(null)

  const requestConfirm = useCallback((message: string) => {
    return new Promise<boolean>((resolve) => {
      setConfirmState({ message, resolve })
    })
  }, [])

  const closeConfirm = useCallback((result: boolean) => {
    setConfirmState((prev) => {
      prev?.resolve(result)
      return null
    })
  }, [])

  const syncRootIndex = useCallback((fetched: RootIndex) => {
    setRootIndex((prev) => {
      if (prev) return prev
      const draft = loadDraftRootIndex()
      return draft ?? cloneRootIndex(fetched)
    })
  }, [])

  const syncBundle = useCallback((langId: string, fetched: LanguageBundle) => {
    setBundles((prev) => {
      if (prev[langId]) return prev
      const draft = loadDraftBundle(langId)
      return { ...prev, [langId]: draft ?? cloneBundle(fetched) }
    })
  }, [])

  const persistRoot = useCallback((next: RootIndex) => {
    setRootIndex(next)
    saveDraftRootIndex(next)
  }, [])

  const persistBundle = useCallback((langId: string, next: LanguageBundle) => {
    setBundles((prev) => ({ ...prev, [langId]: next }))
    saveDraftBundle(langId, next)
  }, [])

  const getBundle = useCallback((langId: string) => bundles[langId] ?? null, [bundles])

  const updateLanguage = useCallback(
    (langId: string, patch: { title?: string; id?: string }) => {
      if (!rootIndex) return
      const next = cloneRootIndex(rootIndex)
      const lang = next.languages.find((l) => l.id === langId)
      if (!lang) return
      if (patch.title !== undefined) lang.title = patch.title
      if (patch.id !== undefined) lang.id = patch.id
      persistRoot(next)
    },
    [rootIndex, persistRoot],
  )

  const updateHomeLead = useCallback((text: string) => {
    setHomeLead(text)
    saveDraftHomeLead(text)
  }, [])

  const updateLanguageTitle = useCallback(
    (langId: string, title: string) => {
      const bundle = bundles[langId]
      if (!bundle) return
      const next = cloneBundle(bundle)
      next.index.title = title
      persistBundle(langId, next)
      updateLanguage(langId, { title })
    },
    [bundles, persistBundle, updateLanguage],
  )

  const updateSectionTitle = useCallback(
    (langId: string, sectionId: string, title: string, options?: { commit?: boolean }) => {
      const bundle = bundles[langId]
      if (!bundle) return
      let next = cloneBundle(bundle)
      const secRef = next.index.sections.find((s) => s.id === sectionId)
      const loaded = next.sections.find((s) => s.sectionRef.id === sectionId)
      if (secRef) secRef.title = title
      if (loaded) {
        loaded.sectionRef.title = title
        loaded.file.title = title
      }

      if (options?.commit && isAutoGeneratedSectionId(sectionId)) {
        const slug = slugifySectionTitle(title)
        if (slug) {
          const taken = next.index.sections.map((s) => s.id).filter((id) => id !== sectionId)
          const newId = uniqueSectionSlug(slug, taken)
          if (newId !== sectionId) {
            next = renameSectionInBundle(next, sectionId, newId, title)
          }
        }
      }

      persistBundle(langId, next)
    },
    [bundles, persistBundle],
  )

  const updateLevelTitle = useCallback(
    (langId: string, sectionId: string, levelId: string, title: string) => {
      const bundle = bundles[langId]
      if (!bundle) return
      const next = patchBundle(bundle, sectionId, levelId, (lvl) => ({ ...lvl, title }))
      persistBundle(langId, next)
    },
    [bundles, persistBundle],
  )

  const updateLevelIntro = useCallback(
    (
      langId: string,
      sectionId: string,
      levelId: string,
      patch: Partial<Level['intro']>,
    ) => {
      const bundle = bundles[langId]
      if (!bundle) return
      const next = patchBundle(bundle, sectionId, levelId, (lvl) => ({
        ...lvl,
        intro: { ...lvl.intro, ...patch },
      }))
      persistBundle(langId, next)
    },
    [bundles, persistBundle],
  )

  const updateChallenge = useCallback(
    (
      langId: string,
      sectionId: string,
      levelId: string,
      challengeId: string,
      patch: Partial<Challenge>,
    ) => {
      const bundle = bundles[langId]
      if (!bundle) return
      const next = patchBundle(bundle, sectionId, levelId, (lvl) => ({
        ...lvl,
        challenges: lvl.challenges.map((ch) =>
          ch.id === challengeId ? { ...ch, ...patch } : ch,
        ),
      }))
      persistBundle(langId, next)
    },
    [bundles, persistBundle],
  )

  const updateTestPassingScore = useCallback(
    (langId: string, sectionId: string, levelId: string, score: number) => {
      const bundle = bundles[langId]
      if (!bundle) return
      const next = patchBundle(bundle, sectionId, levelId, (lvl) => ({
        ...lvl,
        test: { ...lvl.test, passingScorePercent: score },
      }))
      persistBundle(langId, next)
    },
    [bundles, persistBundle],
  )

  const updateTestQuestion = useCallback(
    (
      langId: string,
      sectionId: string,
      levelId: string,
      questionId: string,
      question: TestQuestion,
    ) => {
      const bundle = bundles[langId]
      if (!bundle) return
      const next = patchBundle(bundle, sectionId, levelId, (lvl) => ({
        ...lvl,
        test: {
          ...lvl.test,
          questions: lvl.test.questions.map((q) => (q.id === questionId ? question : q)),
        },
      }))
      persistBundle(langId, next)
    },
    [bundles, persistBundle],
  )

  const applySectionLevelsPatch = useCallback(
    (
      langId: string,
      sectionId: string,
      patchLevels: (levels: Level[]) => Level[],
    ): LanguageBundle | null => {
      const bundle = bundles[langId]
      if (!bundle) return null
      return patchBundleSectionLevels(bundle, sectionId, patchLevels)
    },
    [bundles],
  )

  const addLanguage = useCallback((): string | null => {
    if (!rootIndex) return null
    const langId = newId('lang')
    const { rootEntry, bundle } = createDefaultLanguage(langId)
    const nextRoot = cloneRootIndex(rootIndex)
    nextRoot.languages.push(rootEntry)
    persistRoot(nextRoot)
    persistBundle(langId, bundle)
    return langId
  }, [rootIndex, persistRoot, persistBundle])

  const removeLanguage = useCallback(
    (langId: string) => {
      if (!rootIndex) return
      const nextRoot = cloneRootIndex(rootIndex)
      nextRoot.languages = nextRoot.languages.filter((l) => l.id !== langId)
      persistRoot(nextRoot)
      setBundles((prev) => {
        const next = { ...prev }
        delete next[langId]
        return next
      })
    },
    [rootIndex, persistRoot],
  )

  const moveLanguage = useCallback(
    (langId: string, direction: -1 | 1) => {
      if (!rootIndex) return
      const index = rootIndex.languages.findIndex((l) => l.id === langId)
      if (index < 0) return
      const nextRoot = cloneRootIndex(rootIndex)
      nextRoot.languages = moveItem(nextRoot.languages, index, direction)
      persistRoot(nextRoot)
    },
    [rootIndex, persistRoot],
  )

  const addSection = useCallback(
    (langId: string): string | null => {
      const bundle = bundles[langId]
      if (!bundle) return null
      const { sectionId, path, sectionFile } = createDefaultSection()
      const next = cloneBundle(bundle)
      next.index.sections.push({ id: sectionId, title: sectionFile.title ?? '', path })
      next.sections.push({
        sectionRef: { id: sectionId, title: sectionFile.title ?? '', path },
        file: sectionFile,
      })
      persistBundle(langId, next)
      return sectionId
    },
    [bundles, persistBundle],
  )

  const removeSection = useCallback(
    (langId: string, sectionId: string) => {
      const bundle = bundles[langId]
      if (!bundle) return
      const next = cloneBundle(bundle)
      next.index.sections = next.index.sections.filter((s) => s.id !== sectionId)
      next.sections = next.sections.filter((s) => s.sectionRef.id !== sectionId)
      persistBundle(langId, next)
    },
    [bundles, persistBundle],
  )

  const moveSection = useCallback(
    (langId: string, sectionId: string, direction: -1 | 1) => {
      const bundle = bundles[langId]
      if (!bundle) return
      const index = bundle.index.sections.findIndex((s) => s.id === sectionId)
      if (index < 0) return
      const next = cloneBundle(bundle)
      next.index.sections = moveItem(next.index.sections, index, direction)
      next.sections = moveItem(next.sections, index, direction)
      persistBundle(langId, next)
    },
    [bundles, persistBundle],
  )

  const addLevel = useCallback(
    (langId: string, sectionId: string): string | null => {
      const level = createDefaultLevel()
      const next = applySectionLevelsPatch(langId, sectionId, (levels) => [...levels, level])
      if (!next) return null
      persistBundle(langId, next)
      return level.id
    },
    [applySectionLevelsPatch, persistBundle],
  )

  const removeLevel = useCallback(
    (langId: string, sectionId: string, levelId: string) => {
      const next = applySectionLevelsPatch(langId, sectionId, (levels) =>
        levels.filter((l) => l.id !== levelId),
      )
      if (!next) return
      persistBundle(langId, next)
    },
    [applySectionLevelsPatch, persistBundle],
  )

  const moveLevel = useCallback(
    (langId: string, sectionId: string, levelId: string, direction: -1 | 1) => {
      const bundle = bundles[langId]
      if (!bundle) return
      const section = bundle.sections.find((s) => s.sectionRef.id === sectionId)
      if (!section) return
      const index = section.file.levels.findIndex((l) => l.id === levelId)
      if (index < 0) return
      const next = applySectionLevelsPatch(langId, sectionId, (levels) => moveItem(levels, index, direction))
      if (!next) return
      persistBundle(langId, next)
    },
    [bundles, applySectionLevelsPatch, persistBundle],
  )

  const addChallenge = useCallback(
    (langId: string, sectionId: string, levelId: string): string | null => {
      const challenge = createDefaultChallenge()
      const bundle = bundles[langId]
      if (!bundle) return null
      const next = patchBundle(bundle, sectionId, levelId, (lvl) => ({
        ...lvl,
        challenges: [...lvl.challenges, challenge],
      }))
      persistBundle(langId, next)
      return challenge.id
    },
    [bundles, persistBundle],
  )

  const removeChallenge = useCallback(
    (langId: string, sectionId: string, levelId: string, challengeId: string) => {
      const bundle = bundles[langId]
      if (!bundle) return
      const next = patchBundle(bundle, sectionId, levelId, (lvl) => ({
        ...lvl,
        challenges: lvl.challenges.filter((ch) => ch.id !== challengeId),
      }))
      persistBundle(langId, next)
    },
    [bundles, persistBundle],
  )

  const moveChallenge = useCallback(
    (
      langId: string,
      sectionId: string,
      levelId: string,
      challengeId: string,
      direction: -1 | 1,
    ) => {
      const bundle = bundles[langId]
      if (!bundle) return
      const section = bundle.sections.find((s) => s.sectionRef.id === sectionId)
      const level = section?.file.levels.find((l) => l.id === levelId)
      if (!level) return
      const index = level.challenges.findIndex((ch) => ch.id === challengeId)
      if (index < 0) return
      const next = patchBundle(bundle, sectionId, levelId, (lvl) => ({
        ...lvl,
        challenges: moveItem(lvl.challenges, index, direction),
      }))
      persistBundle(langId, next)
    },
    [bundles, persistBundle],
  )

  const addTestQuestion = useCallback(
    (
      langId: string,
      sectionId: string,
      levelId: string,
      type: 'mcq' | 'shortText',
    ): string | null => {
      const question =
        type === 'mcq' ? createDefaultMcqQuestion() : createDefaultShortTextQuestion()
      const bundle = bundles[langId]
      if (!bundle) return null
      const next = patchBundle(bundle, sectionId, levelId, (lvl) => ({
        ...lvl,
        test: { ...lvl.test, questions: [...lvl.test.questions, question] },
      }))
      persistBundle(langId, next)
      return question.id
    },
    [bundles, persistBundle],
  )

  const removeTestQuestion = useCallback(
    (langId: string, sectionId: string, levelId: string, questionId: string) => {
      const bundle = bundles[langId]
      if (!bundle) return
      const next = patchBundle(bundle, sectionId, levelId, (lvl) => ({
        ...lvl,
        test: {
          ...lvl.test,
          questions: lvl.test.questions.filter((q) => q.id !== questionId),
        },
      }))
      persistBundle(langId, next)
    },
    [bundles, persistBundle],
  )

  const moveTestQuestion = useCallback(
    (
      langId: string,
      sectionId: string,
      levelId: string,
      questionId: string,
      direction: -1 | 1,
    ) => {
      const bundle = bundles[langId]
      if (!bundle) return
      const section = bundle.sections.find((s) => s.sectionRef.id === sectionId)
      const level = section?.file.levels.find((l) => l.id === levelId)
      if (!level) return
      const index = level.test.questions.findIndex((q) => q.id === questionId)
      if (index < 0) return
      const next = patchBundle(bundle, sectionId, levelId, (lvl) => ({
        ...lvl,
        test: {
          ...lvl.test,
          questions: moveItem(lvl.test.questions, index, direction),
        },
      }))
      persistBundle(langId, next)
    },
    [bundles, persistBundle],
  )

  const addAboutInstallStep = useCallback(() => {
    setAboutContent((prev) => {
      const next = { ...prev, installSteps: [...prev.installSteps, 'New step'] }
      saveDraftAbout(next)
      return next
    })
  }, [])

  const removeAboutInstallStep = useCallback((index: number) => {
    setAboutContent((prev) => {
      const next = { ...prev, installSteps: removeAt(prev.installSteps, index) }
      saveDraftAbout(next)
      return next
    })
  }, [])

  const moveAboutInstallStep = useCallback((index: number, direction: -1 | 1) => {
    setAboutContent((prev) => {
      const next = { ...prev, installSteps: moveItem(prev.installSteps, index, direction) }
      saveDraftAbout(next)
      return next
    })
  }, [])

  const initAboutContent = useCallback(
    (platformSteps: string[]) => {
      if (aboutInitialized) return
      const draft = loadDraftAbout()
      setAboutContent(mergeAboutContent(platformSteps, draft))
      setAboutInitialized(true)
    },
    [aboutInitialized],
  )

  const updateAboutLead = useCallback((text: string) => {
    setAboutContent((prev) => {
      const next = { ...prev, lead: text }
      saveDraftAbout(next)
      return next
    })
  }, [])

  const updateAboutInstallIntro = useCallback((text: string) => {
    setAboutContent((prev) => {
      const next = { ...prev, installIntro: text }
      saveDraftAbout(next)
      return next
    })
  }, [])

  const updateAboutInstallStep = useCallback((index: number, text: string) => {
    setAboutContent((prev) => {
      const steps = [...prev.installSteps]
      steps[index] = text
      const next = { ...prev, installSteps: steps }
      saveDraftAbout(next)
      return next
    })
  }, [])

  const exportRootIndex = useCallback(() => {
    if (!rootIndex) return
    downloadJson('index.json', rootIndex)
  }, [rootIndex])

  const exportLanguageIndex = useCallback(
    (langId: string) => {
      const bundle = bundles[langId]
      if (!bundle) return
      downloadJson(`${langId}/index.json`, bundle.index)
    },
    [bundles],
  )

  const exportSection = useCallback(
    (langId: string, sectionId: string) => {
      const bundle = bundles[langId]
      if (!bundle) return
      const section = bundle.sections.find((s) => s.sectionRef.id === sectionId)
      if (!section) return
      const filename = section.sectionRef.path.split('/').pop() ?? `${sectionId}.json`
      downloadJson(filename, section.file)
    },
    [bundles],
  )

  const importFromGitHub = useCallback(
    async (baseUrl: string) => {
      const fetchedRoot = await loadRootIndex(baseUrl)
      persistRoot(cloneRootIndex(fetchedRoot))
      for (const lang of fetchedRoot.languages) {
        const bundle = await loadLanguageBundle(baseUrl, lang.path)
        persistBundle(lang.id, cloneBundle(bundle))
      }
      setContentSourceState('local')
      saveContentSource('local')
    },
    [persistRoot, persistBundle],
  )

  const saveToGitHub = useCallback(
    async (onProgress?: (label: string, index: number, total: number) => void) => {
      if (!rootIndex) throw new Error('No local curriculum to save.')
      await saveCurriculumToGitHub(rootIndex, bundles, onProgress)
    },
    [rootIndex, bundles],
  )

  const toggleEditMode = useCallback(() => {
    setEditMode((v) => !v)
  }, [])

  const setContentSource = useCallback((source: ContentSource) => {
    setContentSourceState(source)
    saveContentSource(source)
  }, [])

  const value = useMemo<EditorContextValue>(
    () => ({
      canEdit,
      isEditMode,
      setEditMode,
      toggleEditMode,
      contentSource,
      setContentSource,
      githubHomeLead: DEFAULT_HOME_LEAD,
      rootIndex,
      syncRootIndex,
      updateLanguage,
      updateHomeLead,
      homeLead,
      getBundle,
      syncBundle,
      updateLanguageTitle,
      updateSectionTitle,
      updateLevelTitle,
      updateLevelIntro,
      updateChallenge,
      updateTestPassingScore,
      updateTestQuestion,
      requestConfirm,
      addLanguage,
      removeLanguage,
      moveLanguage,
      addSection,
      removeSection,
      moveSection,
      addLevel,
      removeLevel,
      moveLevel,
      addChallenge,
      removeChallenge,
      moveChallenge,
      addTestQuestion,
      removeTestQuestion,
      moveTestQuestion,
      addAboutInstallStep,
      removeAboutInstallStep,
      moveAboutInstallStep,
      aboutContent,
      initAboutContent,
      updateAboutLead,
      updateAboutInstallIntro,
      updateAboutInstallStep,
      exportRootIndex,
      exportLanguageIndex,
      exportSection,
      importFromGitHub,
      saveToGitHub,
    }),
    [
      canEdit,
      isEditMode,
      toggleEditMode,
      contentSource,
      setContentSource,
      rootIndex,
      syncRootIndex,
      updateLanguage,
      homeLead,
      updateHomeLead,
      getBundle,
      syncBundle,
      updateLanguageTitle,
      updateSectionTitle,
      updateLevelTitle,
      updateLevelIntro,
      updateChallenge,
      updateTestPassingScore,
      updateTestQuestion,
      requestConfirm,
      addLanguage,
      removeLanguage,
      moveLanguage,
      addSection,
      removeSection,
      moveSection,
      addLevel,
      removeLevel,
      moveLevel,
      addChallenge,
      removeChallenge,
      moveChallenge,
      addTestQuestion,
      removeTestQuestion,
      moveTestQuestion,
      addAboutInstallStep,
      removeAboutInstallStep,
      moveAboutInstallStep,
      aboutContent,
      initAboutContent,
      updateAboutLead,
      updateAboutInstallIntro,
      updateAboutInstallStep,
      exportRootIndex,
      exportLanguageIndex,
      exportSection,
      importFromGitHub,
      saveToGitHub,
    ],
  )

  return (
    <EditorContext.Provider value={value}>
      {children}
      <ConfirmDialog
        open={confirmState !== null}
        message={confirmState?.message ?? ''}
        onCancel={() => closeConfirm(false)}
        onConfirm={() => closeConfirm(true)}
      />
    </EditorContext.Provider>
  )
}
